In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [8]:
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [9]:
df.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [11]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [13]:
df.dropna(how='any', inplace=True)

In [14]:
len(df)

7032

In [15]:
df.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85     No  
1               Mailed check          56.95       1889.50     No  
2               Mailed check          53.85        108.15    Yes  
3  Bank transfer (automatic)          42.30       1840.75     No  
4           Electronic check          70.70        151.65    Yes  

[5 rows x 21 columns]

In [16]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [17]:
x = df.drop(['customerID', 'Churn'], axis=1)

In [18]:
y = df.Churn.values

In [19]:
x

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  
0                 Yes           Electronic check           29.85         29.85  
1                  No               Mailed check           56.95       1889.50  
2                 Yes               Mailed check           53.85        108.15  
3                  No  Bank transfer (automatic)           42.30       1840.75  
4                 Yes           Electronic check           70.70        151.65  
...               ...                        ...             ...           ...  
7038              Yes               Mailed check           84.80       1990.50  
7039              Yes    Credit card (automatic)          103.20       7362.90  
7040              Yes           Electronic check           29.60        346.45  
7041              Yes               Mailed check           74.40        306.60  
7042              Yes  Bank transfer (automatic)          105.65       6844.50  

[7032 rows x 19 columns]

In [20]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [21]:
x.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [22]:
X = pd.get_dummies(x, columns=['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'],drop_first=True)

In [23]:
X.head(1)

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
0              0       1           29.85         29.85        False   

   Partner_Yes  Dependents_Yes  PhoneService_Yes  \
0         True           False             False   

   MultipleLines_No phone service  MultipleLines_Yes  ...  \
0                            True              False  ...   

   StreamingTV_No internet service  StreamingTV_Yes  \
0                            False            False   

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                False                False   

   Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
0              False              False                  True   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True   

   PaymentMethod_Mailed check  
0                       False  

[1 rows x 30 columns]

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [25]:
len(x_train)

5274

In [26]:
len(x_test)

1758

In [27]:
#feature scali
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [28]:
x_train_scaled

array([[-0.4469083 , -0.87619402, -1.46820922, ..., -0.52689304,
        -0.71103211,  1.84056708],
       [-0.4469083 , -1.20127649, -0.01121614, ...,  1.8979184 ,
        -0.71103211, -0.54331081],
       [-0.4469083 ,  1.60255979,  1.48385744, ..., -0.52689304,
         1.40640625, -0.54331081],
       ...,
       [-0.4469083 , -1.12000587,  1.13947726, ..., -0.52689304,
        -0.71103211,  1.84056708],
       [-0.4469083 , -1.28254711, -0.68176409, ..., -0.52689304,
        -0.71103211,  1.84056708],
       [-0.4469083 ,  1.56192448,  1.7851901 , ..., -0.52689304,
         1.40640625, -0.54331081]])

In [29]:
x_test_scaled

array([[-0.4469083 , -0.14475847,  1.18583613, ..., -0.52689304,
        -0.71103211, -0.54331081],
       [-0.4469083 , -1.28254711,  0.22554524, ..., -0.52689304,
        -0.71103211,  1.84056708],
       [-0.4469083 ,  0.78985362,  0.13282749, ..., -0.52689304,
         1.40640625, -0.54331081],
       ...,
       [-0.4469083 , -0.42920563, -1.51291242, ..., -0.52689304,
        -0.71103211, -0.54331081],
       [-0.4469083 , -0.34793501,  1.0351698 , ..., -0.52689304,
         1.40640625, -0.54331081],
       [-0.4469083 , -0.10412316, -0.80759531, ...,  1.8979184 ,
        -0.71103211, -0.54331081]])

Decision Tree Classifier




In [30]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [31]:
y_prediction = model.predict(x_test_scaled)

In [32]:
y_prediction

array(['Yes', 'No', 'No', ..., 'No', 'Yes', 'No'], dtype=object)

In [33]:
y_test

array(['No', 'Yes', 'No', ..., 'No', 'Yes', 'No'], dtype=object)

In [34]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_prediction))

0.7554038680318543


New Data Prediction


In [35]:
x_test_scaled

array([[-0.4469083 , -0.14475847,  1.18583613, ..., -0.52689304,
        -0.71103211, -0.54331081],
       [-0.4469083 , -1.28254711,  0.22554524, ..., -0.52689304,
        -0.71103211,  1.84056708],
       [-0.4469083 ,  0.78985362,  0.13282749, ..., -0.52689304,
         1.40640625, -0.54331081],
       ...,
       [-0.4469083 , -0.42920563, -1.51291242, ..., -0.52689304,
        -0.71103211, -0.54331081],
       [-0.4469083 , -0.34793501,  1.0351698 , ..., -0.52689304,
         1.40640625, -0.54331081],
       [-0.4469083 , -0.10412316, -0.80759531, ...,  1.8979184 ,
        -0.71103211, -0.54331081]])

In [36]:
x_test.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [37]:
data = [[0, 2, 87, 178, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1]]

In [38]:
data_sc = sc.transform(data)

single = model.predict(data_sc)

print(single)

['Yes']


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [39]:
data_sc = sc.transform(data)

single = model.predict_proba(data_sc)

print(single)

[[0.4 0.6]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Decision Tree Classifier

In [40]:
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier()
model_dt.fit(x_train_scaled, y_train)

DecisionTreeClassifier()

In [41]:
y_pred_dt = model_dt.predict(x_test_scaled)

In [42]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_dt))

0.7241183162684869


Ensemble Learning


Ada Boost

In [43]:
from sklearn.ensemble import AdaBoostClassifier
model_ada = AdaBoostClassifier()
model_ada.fit(x_train_scaled, y_train)
y_pred_ada = model_ada.predict(x_test_scaled)

In [44]:
print("accuracy of Adaboost:", accuracy_score(y_test, y_pred_ada))

accuracy of Adaboost: 0.7775881683731513


Gradient Boost

In [45]:
from sklearn.ensemble import GradientBoostingClassifier
model_gb = GradientBoostingClassifier()
model_gb.fit(x_train_scaled, y_train)
y_pred_gb = model_gb.predict(x_test_scaled)

In [46]:
print("accuracy of Gradient Boost:", accuracy_score(y_test, y_pred_gb))

accuracy of Gradient Boost: 0.7872582480091013


XG Boost

In [48]:
from xgboost import XGBClassifier

# Convert 'No' to 0 and 'Yes' to 1 for y_train and y_test
y_train_encoded = np.where(y_train == 'Yes', 1, 0)
y_test_encoded = np.where(y_test == 'Yes', 1, 0)

model_xgb = XGBClassifier()
model_xgb.fit(x_train_scaled, y_train_encoded)
y_pred_xgb = model_xgb.predict(x_test_scaled)

In [50]:
print("Accuracy of XGBoost:", accuracy_score(y_test_encoded, y_pred_xgb))

Accuracy of XGBoost: 0.7815699658703071


In [51]:
y[y=='No'] = 0
y[y=='Yes'] = 1

In [52]:
y

array([0, 0, 1, ..., 0, 1, 0], dtype=object)

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

# Converting data to integer
y_test = y_test.astype(int)
y_train = y_train.astype(int)

# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [54]:
# Call the XGB Classifier
from xgboost import XGBClassifier

# Initiating the classifier
model_xgb = XGBClassifier(n_estimators=100, max_depth=4,learning_rate=0.1)

# Passing the data to classifier
model_xgb.fit(X_train_sc, y_train)

# Predictions
y_pred_xgb = model_xgb.predict(X_test_sc)

In [55]:
print("Accuracy of XGB: ", accuracy_score(y_test, y_pred_xgb))

Accuracy of XGB:  0.8020477815699659
